[build]
  # Install Python deps and run the scraper to create /public JSON.
  command = "pip install -r scraper/requirements.txt && python scraper/dump_understat.py"
  publish = "public"

# Set CORS/headers on all files we serve (JSON etc.)
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Content-Type = "application/json; charset=utf-8"
